package com.edu.educational_system.controller;

public enum CommandName {

	CREATECOURSE, REGISTERPERSON, STARTLESSON, GETAVERAGEGRADE, GETCATALOG, SAVECOURSE, DELETEPERSONALDATA, GETCOURSE, WRONG_REQUEST;

}
